version: '2'

services:
  zookeeper-server:
    image: 'bitnami/zookeeper:3.7'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "PLAINTEXT://kafka-server1:9092,PLAINTEXT://kafka-server2:9092,PLAINTEXT://kafka-server3:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka-server1"
      - "kafka-server2"
      - "kafka-server3"
  kafka-server1:
    image: 'bitnami/kafka:3'
    container_name: kafka-server1
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NUM_PARTITIONS=3
    depends_on:
      - zookeeper-server
    healthcheck:
      test:
        ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "127.0.0.1:9092"]
      interval: 60s
      timeout: 120s
      retries: 4
  kafka-server2:
    image: 'bitnami/kafka:3'
    container_name: kafka-server2
    ports:
      - '9093:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NUM_PARTITIONS=3
    depends_on:
      - zookeeper-server
    healthcheck:
      test:
        ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "127.0.0.1:9092"]
      interval: 60s
      timeout: 120s
      retries: 4
  kafka-server3:
    image: 'bitnami/kafka:3'
    container_name: kafka-server3
    ports:
      - '9094:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NUM_PARTITIONS=3
    depends_on:
      - zookeeper-server
    healthcheck:
      test:
        ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "127.0.0.1:9092"]
      interval: 60s
      timeout: 120s
      retries: 4
