ROM confluent/platform

MAINTAINER contact@confluent.io

COPY ../schema-registry/schema-registry-docker.sh /usr/local/bin/
COPY ../schema-registry/schema-registry.properties /etc/schema-registry/

#TODO Schema Registry needs a log directory.
RUN ["chown", "-R", "confluent:confluent", "/etc/schema-registry/schema-registry.properties"]
RUN ["chmod", "+x", "/usr/local/bin/schema-registry-docker.sh"]

EXPOSE 8081

USER confluent
ENTRYPOINT ["/usr/local/bin/schema-registry-docker.sh"]
